# Generated by Django 4.2.3 on 2024-06-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='picture',
            new_name='image',
        ),
    ]
