# Generated by Django 4.2.3 on 2024-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_picture_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='camera_id',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
