# Generated by Django 4.2.3 on 2024-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_images_camera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='extract_text',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
